import { prisma } from "@/lib/prisma";

type ChecklistItem = { descripcion: string; orden: number; sentido: string };
type ChecklistDef = {
  codigo: string; areaCodigo: string; nombre: string;
  disciplina: string; nivelTag: number | null; areaProceso: string;
  categoriaISO: string | null; items: ChecklistItem[];
};

// Checklists ISO 14224 exportados desde MongoDB
const ISO_CHECKLISTS: ChecklistDef[] = [
  { codigo:"MEC-GEN-CHA", areaCodigo:"*", nombre:"Mecánico — Chancado (ISO 14224)", disciplina:"Mecanico", nivelTag:5, areaProceso:"chancado", categoriaISO:null, items:[
    {descripcion:"Fugas de aceite, grasa, agua o pulpa",orden:1,sentido:"Visual"},
    {descripcion:"Correas, cadenas o acoples desgastados o rotos",orden:2,sentido:"Visual"},
    {descripcion:"Pernos o tornillos flojos",orden:3,sentido:"Visual"},
    {descripcion:"Guardas de seguridad instaladas y en buen estado",orden:4,sentido:"Visual"},
    {descripcion:"Nivel de aceite en mirilla (si aplica)",orden:5,sentido:"Visual"},
    {descripcion:"Ruido a golpeteo (rodamiento dañado)",orden:6,sentido:"Auditivo"},
    {descripcion:"Chirrido (falta lubricación)",orden:7,sentido:"Auditivo"},
    {descripcion:"Rozamiento metálico (desalineación)",orden:8,sentido:"Auditivo"},
    {descripcion:"Olor a grasa quemada o sobrecalentamiento",orden:9,sentido:"Olfativo"},
    {descripcion:"Temperatura anormal (dorso de mano cerca, sin contacto)",orden:10,sentido:"Tactil"},
    {descripcion:"Vibración excesiva (apoyar base de palma en estructura)",orden:11,sentido:"Tactil"},
    {descripcion:"Pasadores o camisas del chancador — desgaste visible",orden:12,sentido:"Visual"},
    {descripcion:"Correas transportadoras centradas y sin daño en bordes",orden:13,sentido:"Visual"},
    {descripcion:"Tolva de alimentación sin atoros ni acumulación excesiva",orden:14,sentido:"Visual"},
    {descripcion:"Imán o separador metálico operativo (luz piloto verde)",orden:15,sentido:"Visual"},
    {descripcion:"Golpeteo irregular en la cámara de chancado",orden:16,sentido:"Auditivo"},
  ]},
  { codigo:"MEC-GEN-MOL", areaCodigo:"*", nombre:"Mecánico — Molienda (ISO 14224)", disciplina:"Mecanico", nivelTag:5, areaProceso:"molienda", categoriaISO:null, items:[
    {descripcion:"Fugas de aceite, grasa, agua o pulpa",orden:1,sentido:"Visual"},
    {descripcion:"Correas, cadenas o acoples desgastados o rotos",orden:2,sentido:"Visual"},
    {descripcion:"Pernos o tornillos flojos",orden:3,sentido:"Visual"},
    {descripcion:"Guardas de seguridad instaladas y en buen estado",orden:4,sentido:"Visual"},
    {descripcion:"Nivel de aceite en mirilla (si aplica)",orden:5,sentido:"Visual"},
    {descripcion:"Ruido a golpeteo (rodamiento dañado)",orden:6,sentido:"Auditivo"},
    {descripcion:"Chirrido (falta lubricación)",orden:7,sentido:"Auditivo"},
    {descripcion:"Rozamiento metálico (desalineación)",orden:8,sentido:"Auditivo"},
    {descripcion:"Olor a grasa quemada o sobrecalentamiento",orden:9,sentido:"Olfativo"},
    {descripcion:"Temperatura anormal (dorso de mano cerca, sin contacto)",orden:10,sentido:"Tactil"},
    {descripcion:"Vibración excesiva (apoyar base de palma en estructura)",orden:11,sentido:"Tactil"},
    {descripcion:"Revestimientos (liner) — espesor y fisuras visibles",orden:12,sentido:"Visual"},
    {descripcion:"Trommel (zaranda de descarga) sin roturas ni deformaciones",orden:13,sentido:"Visual"},
    {descripcion:"Cilindro del molino sin fisuras o golpes visibles",orden:14,sentido:"Visual"},
    {descripcion:"Ruido de bolas — patrón irregular o exceso de impacto",orden:15,sentido:"Auditivo"},
    {descripcion:"Vibración excesiva en chumaceras o sellos",orden:16,sentido:"Tactil"},
  ]},
  { codigo:"MEC-GEN-FLO", areaCodigo:"*", nombre:"Mecánico — Flotacion (ISO 14224)", disciplina:"Mecanico", nivelTag:5, areaProceso:"flotacion", categoriaISO:null, items:[
    {descripcion:"Fugas de aceite, grasa, agua o pulpa",orden:1,sentido:"Visual"},
    {descripcion:"Correas, cadenas o acoples desgastados o rotos",orden:2,sentido:"Visual"},
    {descripcion:"Pernos o tornillos flojos",orden:3,sentido:"Visual"},
    {descripcion:"Guardas de seguridad instaladas y en buen estado",orden:4,sentido:"Visual"},
    {descripcion:"Nivel de aceite en mirilla (si aplica)",orden:5,sentido:"Visual"},
    {descripcion:"Ruido a golpeteo (rodamiento dañado)",orden:6,sentido:"Auditivo"},
    {descripcion:"Chirrido (falta lubricación)",orden:7,sentido:"Auditivo"},
    {descripcion:"Rozamiento metálico (desalineación)",orden:8,sentido:"Auditivo"},
    {descripcion:"Olor a grasa quemada o sobrecalentamiento",orden:9,sentido:"Olfativo"},
    {descripcion:"Temperatura anormal (dorso de mano cerca, sin contacto)",orden:10,sentido:"Tactil"},
    {descripcion:"Vibración excesiva (apoyar base de palma en estructura)",orden:11,sentido:"Tactil"},
    {descripcion:"Celdas de flotación — nivel de espuma estable y uniforme",orden:12,sentido:"Visual"},
    {descripcion:"Válvulas de aire de celdas en posición correcta",orden:13,sentido:"Visual"},
    {descripcion:"Tuberías de relave sin obstrucción ni fugas",orden:14,sentido:"Visual"},
    {descripcion:"Mecanismo de agitación (rotor-estator) sin ruido anormal",orden:15,sentido:"Auditivo"},
  ]},
  { codigo:"MEC-GEN-FIL", areaCodigo:"*", nombre:"Mecánico — Filtros (ISO 14224)", disciplina:"Mecanico", nivelTag:5, areaProceso:"filtros", categoriaISO:null, items:[
    {descripcion:"Fugas de aceite, grasa, agua o pulpa",orden:1,sentido:"Visual"},
    {descripcion:"Correas, cadenas o acoples desgastados o rotos",orden:2,sentido:"Visual"},
    {descripcion:"Pernos o tornillos flojos",orden:3,sentido:"Visual"},
    {descripcion:"Guardas de seguridad instaladas y en buen estado",orden:4,sentido:"Visual"},
    {descripcion:"Nivel de aceite en mirilla (si aplica)",orden:5,sentido:"Visual"},
    {descripcion:"Ruido a golpeteo (rodamiento dañado)",orden:6,sentido:"Auditivo"},
    {descripcion:"Chirrido (falta lubricación)",orden:7,sentido:"Auditivo"},
    {descripcion:"Rozamiento metálico (desalineación)",orden:8,sentido:"Auditivo"},
    {descripcion:"Olor a grasa quemada o sobrecalentamiento",orden:9,sentido:"Olfativo"},
    {descripcion:"Temperatura anormal (dorso de mano cerca, sin contacto)",orden:10,sentido:"Tactil"},
    {descripcion:"Vibración excesiva (apoyar base de palma en estructura)",orden:11,sentido:"Tactil"},
    {descripcion:"Telas filtrantes sin roturas ni taponamientos visibles",orden:12,sentido:"Visual"},
    {descripcion:"Sistema de descarga de torta funcionando sin atoros",orden:13,sentido:"Visual"},
    {descripcion:"Fugas en placas, marcos o sellos de cierre",orden:14,sentido:"Visual"},
    {descripcion:"Presión de soplado — registrar valor y comparar con límite",orden:15,sentido:"Instrumental"},
  ]},
  { codigo:"MEC-GEN-AGU", areaCodigo:"*", nombre:"Mecánico — Aguas (ISO 14224)", disciplina:"Mecanico", nivelTag:5, areaProceso:"aguas", categoriaISO:null, items:[
    {descripcion:"Fugas de aceite, grasa, agua o pulpa",orden:1,sentido:"Visual"},
    {descripcion:"Correas, cadenas o acoples desgastados o rotos",orden:2,sentido:"Visual"},
    {descripcion:"Pernos o tornillos flojos",orden:3,sentido:"Visual"},
    {descripcion:"Guardas de seguridad instaladas y en buen estado",orden:4,sentido:"Visual"},
    {descripcion:"Nivel de aceite en mirilla (si aplica)",orden:5,sentido:"Visual"},
    {descripcion:"Ruido a golpeteo (rodamiento dañado)",orden:6,sentido:"Auditivo"},
    {descripcion:"Chirrido (falta lubricación)",orden:7,sentido:"Auditivo"},
    {descripcion:"Rozamiento metálico (desalineación)",orden:8,sentido:"Auditivo"},
    {descripcion:"Olor a grasa quemada o sobrecalentamiento",orden:9,sentido:"Olfativo"},
    {descripcion:"Temperatura anormal (dorso de mano cerca, sin contacto)",orden:10,sentido:"Tactil"},
    {descripcion:"Vibración excesiva (apoyar base de palma en estructura)",orden:11,sentido:"Tactil"},
    {descripcion:"Bombas de agua — prensa de empaquetadura sin fuga excesiva",orden:12,sentido:"Visual"},
    {descripcion:"Nivel de estanques o espesadores dentro de rango operacional",orden:13,sentido:"Visual"},
    {descripcion:"Tuberías sin fugas visibles ni corrosión avanzada",orden:14,sentido:"Visual"},
    {descripcion:"Sistema de dosificación de floculante operativo",orden:15,sentido:"Visual"},
  ]},
  { codigo:"MEC-GEN-GEN", areaCodigo:"*", nombre:"Mecánico — General (ISO 14224)", disciplina:"Mecanico", nivelTag:5, areaProceso:"general", categoriaISO:null, items:[
    {descripcion:"Fugas de aceite, grasa, agua o pulpa",orden:1,sentido:"Visual"},
    {descripcion:"Correas, cadenas o acoples desgastados o rotos",orden:2,sentido:"Visual"},
    {descripcion:"Pernos o tornillos flojos",orden:3,sentido:"Visual"},
    {descripcion:"Guardas de seguridad instaladas y en buen estado",orden:4,sentido:"Visual"},
    {descripcion:"Nivel de aceite en mirilla (si aplica)",orden:5,sentido:"Visual"},
    {descripcion:"Ruido a golpeteo (rodamiento dañado)",orden:6,sentido:"Auditivo"},
    {descripcion:"Chirrido (falta lubricación)",orden:7,sentido:"Auditivo"},
    {descripcion:"Rozamiento metálico (desalineación)",orden:8,sentido:"Auditivo"},
    {descripcion:"Olor a grasa quemada o sobrecalentamiento",orden:9,sentido:"Olfativo"},
    {descripcion:"Temperatura anormal (dorso de mano cerca, sin contacto)",orden:10,sentido:"Tactil"},
    {descripcion:"Vibración excesiva (apoyar base de palma en estructura)",orden:11,sentido:"Tactil"},
  ]},
  { codigo:"ELE-GEN-CHA", areaCodigo:"*", nombre:"Eléctrico — Chancado (ISO 14224)", disciplina:"Electrico", nivelTag:5, areaProceso:"chancado", categoriaISO:null, items:[
    {descripcion:"Fugas de aceite, grasa, agua o pulpa",orden:1,sentido:"Visual"},
    {descripcion:"Correas, cadenas o acoples desgastados o rotos",orden:2,sentido:"Visual"},
    {descripcion:"Pernos o tornillos flojos",orden:3,sentido:"Visual"},
    {descripcion:"Guardas de seguridad instaladas y en buen estado",orden:4,sentido:"Visual"},
    {descripcion:"Nivel de aceite en mirilla (si aplica)",orden:5,sentido:"Visual"},
    {descripcion:"Ruido a golpeteo (rodamiento dañado)",orden:6,sentido:"Auditivo"},
    {descripcion:"Chirrido (falta lubricación)",orden:7,sentido:"Auditivo"},
    {descripcion:"Rozamiento metálico (desalineación)",orden:8,sentido:"Auditivo"},
    {descripcion:"Olor a grasa quemada o sobrecalentamiento",orden:9,sentido:"Olfativo"},
    {descripcion:"Temperatura anormal (dorso de mano cerca, sin contacto)",orden:10,sentido:"Tactil"},
    {descripcion:"Vibración excesiva (apoyar base de palma en estructura)",orden:11,sentido:"Tactil"},
    {descripcion:"Cableado suelto o conexiones calientes (color café o decolorado)",orden:12,sentido:"Visual"},
    {descripcion:"Aislamiento dañado o pelado",orden:13,sentido:"Visual"},
    {descripcion:"Polvo o suciedad dentro de tableros o cajas de conexión",orden:14,sentido:"Visual"},
    {descripcion:"Luces piloto o indicadores en tablero funcionando",orden:15,sentido:"Visual"},
    {descripcion:"Fusibles soplados o térmicos disparados",orden:16,sentido:"Visual"},
    {descripcion:"Zumbido anormal en contactores o transformadores",orden:17,sentido:"Auditivo"},
    {descripcion:"Olor a quemado (aislante o plástico)",orden:18,sentido:"Olfativo"},
    {descripcion:"Temperatura en bornes o conexiones (dorso de mano)",orden:19,sentido:"Tactil"},
    {descripcion:"Amperaje en pantalla o panel (registrar valor si visible)",orden:20,sentido:"Instrumental"},
    {descripcion:"Pasadores o camisas del chancador — desgaste visible",orden:21,sentido:"Visual"},
    {descripcion:"Correas transportadoras centradas y sin daño en bordes",orden:22,sentido:"Visual"},
    {descripcion:"Tolva de alimentación sin atoros ni acumulación excesiva",orden:23,sentido:"Visual"},
    {descripcion:"Imán o separador metálico operativo (luz piloto verde)",orden:24,sentido:"Visual"},
    {descripcion:"Golpeteo irregular en la cámara de chancado",orden:25,sentido:"Auditivo"},
  ]},
  { codigo:"ELE-GEN-MOL", areaCodigo:"*", nombre:"Eléctrico — Molienda (ISO 14224)", disciplina:"Electrico", nivelTag:5, areaProceso:"molienda", categoriaISO:null, items:[
    {descripcion:"Fugas de aceite, grasa, agua o pulpa",orden:1,sentido:"Visual"},
    {descripcion:"Correas, cadenas o acoples desgastados o rotos",orden:2,sentido:"Visual"},
    {descripcion:"Pernos o tornillos flojos",orden:3,sentido:"Visual"},
    {descripcion:"Guardas de seguridad instaladas y en buen estado",orden:4,sentido:"Visual"},
    {descripcion:"Nivel de aceite en mirilla (si aplica)",orden:5,sentido:"Visual"},
    {descripcion:"Ruido a golpeteo (rodamiento dañado)",orden:6,sentido:"Auditivo"},
    {descripcion:"Chirrido (falta lubricación)",orden:7,sentido:"Auditivo"},
    {descripcion:"Rozamiento metálico (desalineación)",orden:8,sentido:"Auditivo"},
    {descripcion:"Olor a grasa quemada o sobrecalentamiento",orden:9,sentido:"Olfativo"},
    {descripcion:"Temperatura anormal (dorso de mano cerca, sin contacto)",orden:10,sentido:"Tactil"},
    {descripcion:"Vibración excesiva (apoyar base de palma en estructura)",orden:11,sentido:"Tactil"},
    {descripcion:"Cableado suelto o conexiones calientes (color café o decolorado)",orden:12,sentido:"Visual"},
    {descripcion:"Aislamiento dañado o pelado",orden:13,sentido:"Visual"},
    {descripcion:"Polvo o suciedad dentro de tableros o cajas de conexión",orden:14,sentido:"Visual"},
    {descripcion:"Luces piloto o indicadores en tablero funcionando",orden:15,sentido:"Visual"},
    {descripcion:"Fusibles soplados o térmicos disparados",orden:16,sentido:"Visual"},
    {descripcion:"Zumbido anormal en contactores o transformadores",orden:17,sentido:"Auditivo"},
    {descripcion:"Olor a quemado (aislante o plástico)",orden:18,sentido:"Olfativo"},
    {descripcion:"Temperatura en bornes o conexiones (dorso de mano)",orden:19,sentido:"Tactil"},
    {descripcion:"Amperaje en pantalla o panel (registrar valor si visible)",orden:20,sentido:"Instrumental"},
    {descripcion:"Revestimientos (liner) — espesor y fisuras visibles",orden:21,sentido:"Visual"},
    {descripcion:"Trommel (zaranda de descarga) sin roturas ni deformaciones",orden:22,sentido:"Visual"},
    {descripcion:"Cilindro del molino sin fisuras o golpes visibles",orden:23,sentido:"Visual"},
    {descripcion:"Ruido de bolas — patrón irregular o exceso de impacto",orden:24,sentido:"Auditivo"},
    {descripcion:"Vibración excesiva en chumaceras o sellos",orden:25,sentido:"Tactil"},
  ]},
  { codigo:"ELE-GEN-FLO", areaCodigo:"*", nombre:"Eléctrico — Flotacion (ISO 14224)", disciplina:"Electrico", nivelTag:5, areaProceso:"flotacion", categoriaISO:null, items:[
    {descripcion:"Fugas de aceite, grasa, agua o pulpa",orden:1,sentido:"Visual"},
    {descripcion:"Correas, cadenas o acoples desgastados o rotos",orden:2,sentido:"Visual"},
    {descripcion:"Pernos o tornillos flojos",orden:3,sentido:"Visual"},
    {descripcion:"Guardas de seguridad instaladas y en buen estado",orden:4,sentido:"Visual"},
    {descripcion:"Nivel de aceite en mirilla (si aplica)",orden:5,sentido:"Visual"},
    {descripcion:"Ruido a golpeteo (rodamiento dañado)",orden:6,sentido:"Auditivo"},
    {descripcion:"Chirrido (falta lubricación)",orden:7,sentido:"Auditivo"},
    {descripcion:"Rozamiento metálico (desalineación)",orden:8,sentido:"Auditivo"},
    {descripcion:"Olor a grasa quemada o sobrecalentamiento",orden:9,sentido:"Olfativo"},
    {descripcion:"Temperatura anormal (dorso de mano cerca, sin contacto)",orden:10,sentido:"Tactil"},
    {descripcion:"Vibración excesiva (apoyar base de palma en estructura)",orden:11,sentido:"Tactil"},
    {descripcion:"Cableado suelto o conexiones calientes (color café o decolorado)",orden:12,sentido:"Visual"},
    {descripcion:"Aislamiento dañado o pelado",orden:13,sentido:"Visual"},
    {descripcion:"Polvo o suciedad dentro de tableros o cajas de conexión",orden:14,sentido:"Visual"},
    {descripcion:"Luces piloto o indicadores en tablero funcionando",orden:15,sentido:"Visual"},
    {descripcion:"Fusibles soplados o térmicos disparados",orden:16,sentido:"Visual"},
    {descripcion:"Zumbido anormal en contactores o transformadores",orden:17,sentido:"Auditivo"},
    {descripcion:"Olor a quemado (aislante o plástico)",orden:18,sentido:"Olfativo"},
    {descripcion:"Temperatura en bornes o conexiones (dorso de mano)",orden:19,sentido:"Tactil"},
    {descripcion:"Amperaje en pantalla o panel (registrar valor si visible)",orden:20,sentido:"Instrumental"},
    {descripcion:"Celdas de flotación — nivel de espuma estable y uniforme",orden:21,sentido:"Visual"},
    {descripcion:"Válvulas de aire de celdas en posición correcta",orden:22,sentido:"Visual"},
    {descripcion:"Tuberías de relave sin obstrucción ni fugas",orden:23,sentido:"Visual"},
    {descripcion:"Mecanismo de agitación (rotor-estator) sin ruido anormal",orden:24,sentido:"Auditivo"},
  ]},
  { codigo:"ELE-GEN-FIL", areaCodigo:"*", nombre:"Eléctrico — Filtros (ISO 14224)", disciplina:"Electrico", nivelTag:5, areaProceso:"filtros", categoriaISO:null, items:[
    {descripcion:"Fugas de aceite, grasa, agua o pulpa",orden:1,sentido:"Visual"},
    {descripcion:"Correas, cadenas o acoples desgastados o rotos",orden:2,sentido:"Visual"},
    {descripcion:"Pernos o tornillos flojos",orden:3,sentido:"Visual"},
    {descripcion:"Guardas de seguridad instaladas y en buen estado",orden:4,sentido:"Visual"},
    {descripcion:"Nivel de aceite en mirilla (si aplica)",orden:5,sentido:"Visual"},
    {descripcion:"Ruido a golpeteo (rodamiento dañado)",orden:6,sentido:"Auditivo"},
    {descripcion:"Chirrido (falta lubricación)",orden:7,sentido:"Auditivo"},
    {descripcion:"Rozamiento metálico (desalineación)",orden:8,sentido:"Auditivo"},
    {descripcion:"Olor a grasa quemada o sobrecalentamiento",orden:9,sentido:"Olfativo"},
    {descripcion:"Temperatura anormal (dorso de mano cerca, sin contacto)",orden:10,sentido:"Tactil"},
    {descripcion:"Vibración excesiva (apoyar base de palma en estructura)",orden:11,sentido:"Tactil"},
    {descripcion:"Cableado suelto o conexiones calientes (color café o decolorado)",orden:12,sentido:"Visual"},
    {descripcion:"Aislamiento dañado o pelado",orden:13,sentido:"Visual"},
    {descripcion:"Polvo o suciedad dentro de tableros o cajas de conexión",orden:14,sentido:"Visual"},
    {descripcion:"Luces piloto o indicadores en tablero funcionando",orden:15,sentido:"Visual"},
    {descripcion:"Fusibles soplados o térmicos disparados",orden:16,sentido:"Visual"},
    {descripcion:"Zumbido anormal en contactores o transformadores",orden:17,sentido:"Auditivo"},
    {descripcion:"Olor a quemado (aislante o plástico)",orden:18,sentido:"Olfativo"},
    {descripcion:"Temperatura en bornes o conexiones (dorso de mano)",orden:19,sentido:"Tactil"},
    {descripcion:"Amperaje en pantalla o panel (registrar valor si visible)",orden:20,sentido:"Instrumental"},
    {descripcion:"Telas filtrantes sin roturas ni taponamientos visibles",orden:21,sentido:"Visual"},
    {descripcion:"Sistema de descarga de torta funcionando sin atoros",orden:22,sentido:"Visual"},
    {descripcion:"Fugas en placas, marcos o sellos de cierre",orden:23,sentido:"Visual"},
    {descripcion:"Presión de soplado — registrar valor y comparar con límite",orden:24,sentido:"Instrumental"},
  ]},
  { codigo:"ELE-GEN-AGU", areaCodigo:"*", nombre:"Eléctrico — Aguas (ISO 14224)", disciplina:"Electrico", nivelTag:5, areaProceso:"aguas", categoriaISO:null, items:[
    {descripcion:"Fugas de aceite, grasa, agua o pulpa",orden:1,sentido:"Visual"},
    {descripcion:"Correas, cadenas o acoples desgastados o rotos",orden:2,sentido:"Visual"},
    {descripcion:"Pernos o tornillos flojos",orden:3,sentido:"Visual"},
    {descripcion:"Guardas de seguridad instaladas y en buen estado",orden:4,sentido:"Visual"},
    {descripcion:"Nivel de aceite en mirilla (si aplica)",orden:5,sentido:"Visual"},
    {descripcion:"Ruido a golpeteo (rodamiento dañado)",orden:6,sentido:"Auditivo"},
    {descripcion:"Chirrido (falta lubricación)",orden:7,sentido:"Auditivo"},
    {descripcion:"Rozamiento metálico (desalineación)",orden:8,sentido:"Auditivo"},
    {descripcion:"Olor a grasa quemada o sobrecalentamiento",orden:9,sentido:"Olfativo"},
    {descripcion:"Temperatura anormal (dorso de mano cerca, sin contacto)",orden:10,sentido:"Tactil"},
    {descripcion:"Vibración excesiva (apoyar base de palma en estructura)",orden:11,sentido:"Tactil"},
    {descripcion:"Cableado suelto o conexiones calientes (color café o decolorado)",orden:12,sentido:"Visual"},
    {descripcion:"Aislamiento dañado o pelado",orden:13,sentido:"Visual"},
    {descripcion:"Polvo o suciedad dentro de tableros o cajas de conexión",orden:14,sentido:"Visual"},
    {descripcion:"Luces piloto o indicadores en tablero funcionando",orden:15,sentido:"Visual"},
    {descripcion:"Fusibles soplados o térmicos disparados",orden:16,sentido:"Visual"},
    {descripcion:"Zumbido anormal en contactores o transformadores",orden:17,sentido:"Auditivo"},
    {descripcion:"Olor a quemado (aislante o plástico)",orden:18,sentido:"Olfativo"},
    {descripcion:"Temperatura en bornes o conexiones (dorso de mano)",orden:19,sentido:"Tactil"},
    {descripcion:"Amperaje en pantalla o panel (registrar valor si visible)",orden:20,sentido:"Instrumental"},
    {descripcion:"Bombas de agua — prensa de empaquetadura sin fuga excesiva",orden:21,sentido:"Visual"},
    {descripcion:"Nivel de estanques o espesadores dentro de rango operacional",orden:22,sentido:"Visual"},
    {descripcion:"Tuberías sin fugas visibles ni corrosión avanzada",orden:23,sentido:"Visual"},
    {descripcion:"Sistema de dosificación de floculante operativo",orden:24,sentido:"Visual"},
  ]},
  { codigo:"ELE-GEN-GEN", areaCodigo:"*", nombre:"Eléctrico — General (ISO 14224)", disciplina:"Electrico", nivelTag:5, areaProceso:"general", categoriaISO:null, items:[
    {descripcion:"Fugas de aceite, grasa, agua o pulpa",orden:1,sentido:"Visual"},
    {descripcion:"Correas, cadenas o acoples desgastados o rotos",orden:2,sentido:"Visual"},
    {descripcion:"Pernos o tornillos flojos",orden:3,sentido:"Visual"},
    {descripcion:"Guardas de seguridad instaladas y en buen estado",orden:4,sentido:"Visual"},
    {descripcion:"Nivel de aceite en mirilla (si aplica)",orden:5,sentido:"Visual"},
    {descripcion:"Ruido a golpeteo (rodamiento dañado)",orden:6,sentido:"Auditivo"},
    {descripcion:"Chirrido (falta lubricación)",orden:7,sentido:"Auditivo"},
    {descripcion:"Rozamiento metálico (desalineación)",orden:8,sentido:"Auditivo"},
    {descripcion:"Olor a grasa quemada o sobrecalentamiento",orden:9,sentido:"Olfativo"},
    {descripcion:"Temperatura anormal (dorso de mano cerca, sin contacto)",orden:10,sentido:"Tactil"},
    {descripcion:"Vibración excesiva (apoyar base de palma en estructura)",orden:11,sentido:"Tactil"},
    {descripcion:"Cableado suelto o conexiones calientes (color café o decolorado)",orden:12,sentido:"Visual"},
    {descripcion:"Aislamiento dañado o pelado",orden:13,sentido:"Visual"},
    {descripcion:"Polvo o suciedad dentro de tableros o cajas de conexión",orden:14,sentido:"Visual"},
    {descripcion:"Luces piloto o indicadores en tablero funcionando",orden:15,sentido:"Visual"},
    {descripcion:"Fusibles soplados o térmicos disparados",orden:16,sentido:"Visual"},
    {descripcion:"Zumbido anormal en contactores o transformadores",orden:17,sentido:"Auditivo"},
    {descripcion:"Olor a quemado (aislante o plástico)",orden:18,sentido:"Olfativo"},
    {descripcion:"Temperatura en bornes o conexiones (dorso de mano)",orden:19,sentido:"Tactil"},
    {descripcion:"Amperaje en pantalla o panel (registrar valor si visible)",orden:20,sentido:"Instrumental"},
  ]},
  { codigo:"INS-GEN-N5", areaCodigo:"*", nombre:"Instrumentación Nivel 5 (ISO 14224)", disciplina:"Instrumentacion", nivelTag:5, areaProceso:"general", categoriaISO:null, items:[
    {descripcion:"Indicadores locales de presión, temperatura y nivel legibles y en rango",orden:1,sentido:"Visual"},
    {descripcion:"Válvulas en posición correcta (abierto/cerrado según proceso)",orden:2,sentido:"Visual"},
    {descripcion:"Fugas en conexiones de instrumentos (tubing, fittings, sellos)",orden:3,sentido:"Visual"},
    {descripcion:"Pantallas de transmisores sin errores ni alarmas activas",orden:4,sentido:"Visual"},
    {descripcion:"Tubos capilares o líneas de impulso sin daño físico",orden:5,sentido:"Visual"},
    {descripcion:"Escape de aire en válvulas neumáticas (actuadores, posicionadores)",orden:6,sentido:"Auditivo"},
    {descripcion:"Olor a gas o solvente en área del instrumento (si aplica)",orden:7,sentido:"Olfativo"},
    {descripcion:"Vibración excesiva en líneas o soportes de instrumentos",orden:8,sentido:"Tactil"},
  ]},
  { codigo:"INS-GEN-N7", areaCodigo:"*", nombre:"Instrumentación Nivel 7 — Sensor/Transmisor (ISO 14224)", disciplina:"Instrumentacion", nivelTag:7, areaProceso:"general", categoriaISO:null, items:[
    {descripcion:"Indicadores locales de presión, temperatura y nivel legibles y en rango",orden:1,sentido:"Visual"},
    {descripcion:"Válvulas en posición correcta (abierto/cerrado según proceso)",orden:2,sentido:"Visual"},
    {descripcion:"Fugas en conexiones de instrumentos (tubing, fittings, sellos)",orden:3,sentido:"Visual"},
    {descripcion:"Pantallas de transmisores sin errores ni alarmas activas",orden:4,sentido:"Visual"},
    {descripcion:"Tubos capilares o líneas de impulso sin daño físico",orden:5,sentido:"Visual"},
    {descripcion:"Escape de aire en válvulas neumáticas (actuadores, posicionadores)",orden:6,sentido:"Auditivo"},
    {descripcion:"Olor a gas o solvente en área del instrumento (si aplica)",orden:7,sentido:"Olfativo"},
    {descripcion:"Vibración excesiva en líneas o soportes de instrumentos",orden:8,sentido:"Tactil"},
    {descripcion:"Placa de identificación legible y coincide con TAG del sistema",orden:9,sentido:"Visual"},
    {descripcion:"Cableado de señal (4-20 mA / HART) sin daño ni empalmes improvisados",orden:10,sentido:"Visual"},
    {descripcion:"Sello de proceso en buen estado (sin fuga al proceso)",orden:11,sentido:"Visual"},
    {descripcion:"Señal de proceso coincide con valor de referencia local (±5%)",orden:12,sentido:"Instrumental"},
  ]},
  { codigo:"MEC-AGI-FLO", areaCodigo:"*", nombre:"Motor-Agitador — Flotación (ISO 14224)", disciplina:"Mecanico", nivelTag:5, areaProceso:"flotacion", categoriaISO:"AGITADORES", items:[
    {descripcion:"Fugas en sello mecánico del eje del agitador (pulpa o agua)",orden:1,sentido:"Visual"},
    {descripcion:"Estado del rotor-estator — desgaste visible o corrosión",orden:2,sentido:"Visual"},
    {descripcion:"Pernos de fijación del agitador al estanque o celda",orden:3,sentido:"Visual"},
    {descripcion:"Guardas y protecciones del eje instaladas",orden:4,sentido:"Visual"},
    {descripcion:"Ruido a golpeteo o vibración en el eje del agitador",orden:5,sentido:"Auditivo"},
    {descripcion:"Chirrido en rodamiento superior o inferior",orden:6,sentido:"Auditivo"},
    {descripcion:"Temperatura anormal en carcasa del reductor",orden:7,sentido:"Tactil"},
    {descripcion:"Vibración excesiva en estructura de soporte",orden:8,sentido:"Tactil"},
    {descripcion:"Fugas de aceite o grasa en el motor eléctrico",orden:9,sentido:"Visual"},
    {descripcion:"Cableado de alimentación sin daño ni empalmes",orden:10,sentido:"Visual"},
    {descripcion:"Caja de bornes cerrada y sin humedad",orden:11,sentido:"Visual"},
    {descripcion:"Sonido irregular del motor (zumbido o golpeteo)",orden:12,sentido:"Auditivo"},
    {descripcion:"Olor a quemado en motor o bobinado",orden:13,sentido:"Olfativo"},
    {descripcion:"Temperatura anormal en carcasa del motor",orden:14,sentido:"Tactil"},
    {descripcion:"Amperaje en panel o variador (registrar valor si visible)",orden:15,sentido:"Instrumental"},
  ]},
  { codigo:"MEC-MOT-GEN", areaCodigo:"*", nombre:"Motobomba — General (ISO 14224)", disciplina:"Mecanico", nivelTag:5, areaProceso:"general", categoriaISO:"MOTOBOMBAS", items:[
    {descripcion:"Fugas en prensa de empaquetadura o sello mecánico",orden:1,sentido:"Visual"},
    {descripcion:"Corrosión o erosión en carcasa de la bomba",orden:2,sentido:"Visual"},
    {descripcion:"Pernos de fijación bomba-base sin holgura",orden:3,sentido:"Visual"},
    {descripcion:"Guardas del acople instaladas",orden:4,sentido:"Visual"},
    {descripcion:"Cavitación (ruido a grava girando dentro de la bomba)",orden:5,sentido:"Auditivo"},
    {descripcion:"Ruido a golpeteo en rodamientos",orden:6,sentido:"Auditivo"},
    {descripcion:"Temperatura anormal en rodamientos",orden:7,sentido:"Tactil"},
    {descripcion:"Vibración excesiva en carcasa",orden:8,sentido:"Tactil"},
    {descripcion:"Cableado y caja de bornes sin daño ni humedad",orden:9,sentido:"Visual"},
    {descripcion:"Sonido irregular del motor",orden:10,sentido:"Auditivo"},
    {descripcion:"Olor a quemado en motor o bobinado",orden:11,sentido:"Olfativo"},
    {descripcion:"Temperatura anormal en carcasa del motor",orden:12,sentido:"Tactil"},
    {descripcion:"Amperaje en panel (registrar valor si visible)",orden:13,sentido:"Instrumental"},
  ]},
];

export async function POST() {
  try {
    let creados = 0;
    let omitidos = 0;
    const resumen: string[] = [];

    for (const cl of ISO_CHECKLISTS) {
      // Upsert por nombre: si ya existe, actualiza ítems; si no, crea
      const existing = await prisma.checklistMantto.findFirst({
        where: { nombre: cl.nombre },
      });

      if (existing) {
        await prisma.checklistMantto.update({
          where: { id: existing.id },
          data: { items: cl.items, activo: true },
        });
        omitidos++;
      } else {
        await prisma.checklistMantto.create({
          data: {
            codigo:      cl.codigo,
            areaCodigo:  cl.areaCodigo,
            nombre:      cl.nombre,
            disciplina:  cl.disciplina,
            nivelTag:    cl.nivelTag,
            areaProceso: cl.areaProceso,
            categoriaISO: cl.categoriaISO ?? null,
            items:       cl.items,
            activo:      true,
          },
        });
        creados++;
        resumen.push(`✓ ${cl.nombre} (${cl.items.length} ítems)`);
      }
    }

    return Response.json({
      ok: true,
      total: ISO_CHECKLISTS.length,
      creados,
      actualizados: omitidos,
      resumen,
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Error interno";
    return Response.json({ ok: false, error: message }, { status: 500 });
  }
}

export async function GET() {
  return Response.json({ ok: false, error: "Use POST" }, { status: 405 });
}
