import { connectDB } from "@/lib/db";
import { Patron } from "@/lib/models/Patron";

const SEED_DATA = [
  {
    codigo: "BUFORP-001",
    descripcion: "Buffer Redox 220mV ORP",
    tipo: "ORP",
    marca: "YSI",
    modelo: "CPY3-4",
    numeroSerie: "95767131",
    fechaUltimaCalibracion: new Date("2024-12-20"),
    fechaVencimiento: new Date("2026-06-19"),
    frecuenciaCalibracion: "18 meses",
    activo: true,
  },
  {
    codigo: "BUFPH4-001",
    descripcion: "Buffer Solution pH 4",
    tipo: "pH",
    marca: "Thermo Scientific",
    modelo: "SB101-500",
    numeroSerie: "233052",
    fechaUltimaCalibracion: new Date("2023-03-14"),
    fechaVencimiento: new Date("2026-07-31"),
    frecuenciaCalibracion: "2 años",
    activo: true,
  },
  {
    codigo: "BUFPH10-001",
    descripcion: "Buffer Solution pH 10",
    tipo: "pH",
    marca: "Thermo Scientific",
    modelo: "SB115-500",
    numeroSerie: "246172",
    fechaUltimaCalibracion: new Date("2023-01-04"),
    fechaVencimiento: new Date("2026-12-31"),
    frecuenciaCalibracion: "2 años",
    activo: true,
  },
  {
    codigo: "BUFPH7-001",
    descripcion: "Buffer Solution pH 7",
    tipo: "pH",
    marca: "Thermo Scientific",
    modelo: "SB107-500",
    numeroSerie: "243528",
    fechaUltimaCalibracion: new Date("2023-09-13"),
    fechaVencimiento: new Date("2026-07-31"),
    frecuenciaCalibracion: "2 años",
    activo: true,
  },
  {
    codigo: "FLK-700G",
    descripcion: "FLUKE 700G — Manómetro de Presión",
    tipo: "Presión",
    marca: "FLUKE",
    modelo: "700G",
    numeroSerie: "2324031",
    fechaUltimaCalibracion: new Date("2024-09-16"),
    fechaVencimiento: new Date("2026-09-16"),
    frecuenciaCalibracion: "2 años",
    ubicacion: "LP-CCP-0786-2024",
    activo: true,
  },
  {
    codigo: "FLK-700P06",
    descripcion: "FLUKE 700P06 — Módulo de Presión",
    tipo: "Presión",
    marca: "FLUKE",
    modelo: "700P06",
    numeroSerie: "94000610",
    fechaUltimaCalibracion: new Date("2024-08-16"),
    fechaVencimiento: new Date("2026-09-16"),
    frecuenciaCalibracion: "2 años",
    ubicacion: "LP-CCP-0788-2024",
    activo: true,
  },
  {
    codigo: "FLK-700P07",
    descripcion: "FLUKE 700P07 — Módulo de Presión",
    tipo: "Presión",
    marca: "FLUKE",
    modelo: "700P07",
    numeroSerie: "24140701",
    fechaUltimaCalibracion: new Date("2024-09-16"),
    fechaVencimiento: new Date("2026-09-16"),
    frecuenciaCalibracion: "2 años",
    ubicacion: "LP-CCP-0787-2024",
    activo: true,
  },
  {
    codigo: "FLK-700P24",
    descripcion: "FLUKE 700P24 — Módulo de Presión",
    tipo: "Presión",
    marca: "FLUKE",
    modelo: "700P24",
    numeroSerie: "93852410",
    fechaUltimaCalibracion: new Date("2024-09-16"),
    fechaVencimiento: new Date("2026-09-16"),
    frecuenciaCalibracion: "2 años",
    ubicacion: "LP-CCP-0790-2024",
    activo: true,
  },
  {
    codigo: "FLK-700P31",
    descripcion: "FLUKE 700P31 — Módulo de Presión Alta",
    tipo: "Presión",
    marca: "FLUKE",
    modelo: "700P31",
    numeroSerie: "23473105",
    fechaUltimaCalibracion: new Date("2024-09-16"),
    fechaVencimiento: new Date("2026-09-16"),
    frecuenciaCalibracion: "2 años",
    ubicacion: "LP-CCP-0789-2024",
    activo: true,
  },
  {
    codigo: "FLK-744",
    descripcion: "FLUKE 744 — Calibrador de Proceso Multifunción",
    tipo: "Multifunción",
    marca: "FLUKE",
    modelo: "744",
    numeroSerie: "9240004",
    fechaUltimaCalibracion: new Date("2024-09-16"),
    fechaVencimiento: new Date("2026-09-16"),
    frecuenciaCalibracion: "2 años",
    ubicacion: "LP-CCE-0180-2024",
    activo: true,
  },
  {
    codigo: "FLK-9142",
    descripcion: "FLUKE 9142 — Horno de Temperatura de Campo",
    tipo: "Temperatura",
    marca: "FLUKE",
    modelo: "9142",
    numeroSerie: "B01497",
    fechaUltimaCalibracion: new Date("2024-09-17"),
    fechaVencimiento: new Date("2026-09-17"),
    frecuenciaCalibracion: "2 años",
    activo: true,
  },
  {
    codigo: "GAS-HCN10",
    descripcion: "GAS Composición HCN 10 PPM",
    tipo: "Gas",
    marca: "Linde",
    modelo: "HCN 10PPM",
    numeroSerie: "HW304402819454",
    fechaUltimaCalibracion: new Date("2025-01-04"),
    fechaVencimiento: new Date("2026-01-10"),
    frecuenciaCalibracion: "1 año",
    activo: false,
  },
  {
    codigo: "GAS-N2-9999",
    descripcion: "GAS Nitrógeno 99.99%",
    tipo: "Gas",
    marca: "Linde",
    modelo: "N2 99.99%",
    numeroSerie: "302-402229057-29",
    fechaUltimaCalibracion: new Date("2024-01-09"),
    fechaVencimiento: new Date("2029-01-10"),
    frecuenciaCalibracion: "5 años",
    activo: true,
  },
  {
    codigo: "LAB-GRAV-001",
    descripcion: "Lab. Met. Determinación del Porcentaje de Sólidos por Gravimetría",
    tipo: "Masa",
    marca: "FONDONORMA",
    modelo: "Método Gravimétrico",
    numeroSerie: "—",
    fechaUltimaCalibracion: new Date("2025-01-10"),
    fechaVencimiento: new Date("2026-10-31"),
    frecuenciaCalibracion: "1 año",
    activo: true,
  },
  {
    codigo: "MASA-REF-AZUL",
    descripcion: "Masas de Referencia Azul",
    tipo: "Masa",
    marca: "—",
    modelo: "Masas Ref. Azul",
    numeroSerie: "—",
    fechaUltimaCalibracion: new Date("2025-10-21"),
    fechaVencimiento: new Date("2027-10-21"),
    frecuenciaCalibracion: "2 años",
    activo: true,
  },
  {
    codigo: "MASA-IBMET-001",
    descripcion: "Masas Patrón Cert. Ibmetro LP-CCM-285-2021",
    tipo: "Masa",
    marca: "IBMETRO",
    modelo: "LP-CCM-285-2021",
    numeroSerie: "—",
    fechaUltimaCalibracion: new Date("2021-08-23"),
    fechaVencimiento: new Date("2026-08-23"),
    frecuenciaCalibracion: "5 años",
    activo: true,
  },
  {
    codigo: "COND-12880",
    descripcion: "Patrón de Conductividad 12,880 µS/cm",
    tipo: "Conductividad",
    marca: "YSI",
    modelo: "BC4094",
    numeroSerie: "K2622C",
    fechaUltimaCalibracion: new Date("2023-01-03"),
    fechaVencimiento: new Date("2025-01-07"),
    frecuenciaCalibracion: "2 años",
    activo: false,
  },
  {
    codigo: "COND-1413",
    descripcion: "Patrón de Conductividad 1413 µS/cm",
    tipo: "Conductividad",
    marca: "YSI",
    modelo: "BC4094",
    numeroSerie: "C1023B",
    fechaUltimaCalibracion: new Date("2023-02-01"),
    fechaVencimiento: new Date("2025-03-01"),
    frecuenciaCalibracion: "2 años",
    activo: false,
  },
  {
    codigo: "SON-114DB",
    descripcion: "Patrón de Sonido 114 dB",
    tipo: "Sonido",
    marca: "—",
    modelo: "—",
    numeroSerie: "AC300017251",
    fechaUltimaCalibracion: new Date("2023-08-28"),
    fechaVencimiento: new Date("2025-08-28"),
    frecuenciaCalibracion: "2 años",
    activo: false,
  },
  {
    codigo: "TACO-TESTO470",
    descripcion: "Tacómetro TESTO-470",
    tipo: "Velocidad",
    marca: "TESTO",
    modelo: "470",
    numeroSerie: "935021",
    fechaUltimaCalibracion: new Date("2024-08-21"),
    fechaVencimiento: new Date("2026-08-21"),
    frecuenciaCalibracion: "2 años",
    activo: true,
  },
  {
    codigo: "TERM-FLK561",
    descripcion: "Termómetro FLUKE 561",
    tipo: "Temperatura",
    marca: "FLUKE",
    modelo: "561",
    numeroSerie: "55970159WS",
    fechaUltimaCalibracion: new Date("2024-09-17"),
    fechaVencimiento: new Date("2026-09-17"),
    frecuenciaCalibracion: "2 años",
    activo: true,
  },
];

export async function POST() {
  try {
    await connectDB();
    let insertados = 0;
    let actualizados = 0;

    for (const p of SEED_DATA) {
      const result = await Patron.updateOne(
        { codigo: p.codigo },
        { $setOnInsert: p },
        { upsert: true }
      );
      if (result.upsertedCount > 0) insertados++;
      else actualizados++;
    }

    return Response.json({
      ok: true,
      mensaje: `Seed completado: ${insertados} insertados, ${actualizados} ya existían`,
      total: SEED_DATA.length,
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Error interno";
    return Response.json({ ok: false, error: message }, { status: 500 });
  }
}
